/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "HelloWorldReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(helloworld::ChatItemTemplate)
			IMPL_CPP_TYPE_INFO(helloworld::ChatItemTemplateConstructor)
			IMPL_CPP_TYPE_INFO(helloworld::IChat)
			IMPL_CPP_TYPE_INFO(helloworld::IChatGPTViewModel)
			IMPL_CPP_TYPE_INFO(helloworld::MainWindow)
			IMPL_CPP_TYPE_INFO(helloworld::MainWindowConstructor)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_CLASS_MEMBER(::helloworld::ChatItemTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiListItemTemplate)
				CLASS_MEMBER_BASE(::helloworld::ChatItemTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::helloworld::ChatItemTemplate*(::vl::Ptr<::helloworld::IChat>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(__vwsn_instance_ctor_, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::helloworld::ChatItemTemplate)

			BEGIN_CLASS_MEMBER(::helloworld::ChatItemTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::helloworld::ChatItemTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_helloworld_ChatItemTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(ViewModel)
				CLASS_MEMBER_FIELD(contentCell)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::helloworld::ChatItemTemplateConstructor)

			BEGIN_INTERFACE_MEMBER(::helloworld::IChat)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetContent, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetRichContent, NO_PARAMETER)
				CLASS_MEMBER_EVENT(ContentChanged)
				CLASS_MEMBER_EVENT(RichContentChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Content, GetContent, ContentChanged)
				CLASS_MEMBER_FIELD(ContentCell)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(RichContent, GetRichContent, RichContentChanged)
			END_INTERFACE_MEMBER(::helloworld::IChat)

			BEGIN_INTERFACE_MEMBER(::helloworld::IChatGPTViewModel)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(AddChat, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetChats, NO_PARAMETER)
				CLASS_MEMBER_PROPERTY_READONLY(Chats, GetChats)
				CLASS_MEMBER_FIELD(ListView)
			END_INTERFACE_MEMBER(::helloworld::IChatGPTViewModel)

			BEGIN_CLASS_MEMBER(::helloworld::MainWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_BASE(::helloworld::MainWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::helloworld::MainWindow*(::vl::Ptr<::helloworld::IChatGPTViewModel>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::helloworld::MainWindow)

			BEGIN_CLASS_MEMBER(::helloworld::MainWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::helloworld::MainWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_helloworld_MainWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(ViewModel)
				CLASS_MEMBER_FIELD(listViewChats)
			END_CLASS_MEMBER(::helloworld::MainWindowConstructor)

#undef _
			class HelloWorldTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::helloworld::ChatItemTemplate)
					ADD_TYPE_INFO(::helloworld::ChatItemTemplateConstructor)
					ADD_TYPE_INFO(::helloworld::IChat)
					ADD_TYPE_INFO(::helloworld::IChatGPTViewModel)
					ADD_TYPE_INFO(::helloworld::MainWindow)
					ADD_TYPE_INFO(::helloworld::MainWindowConstructor)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadHelloWorldTypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new HelloWorldTypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
